//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ChromiumUpdater.rc
//

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_CHROMIUMUPDATER_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_CHROMIUMUPDATER			107
#define IDI_SMALL				108
#define IDC_CHROMIUMUPDATER			109
#define IDB_LOOKUP_LATEST 110
#define IDE_LATEST_VERSION 111
#define IDB_DOWNLOAD_LATEST 112
#define IDB_INSTALL_LATEST 113
#define IDB_CHECK_INSTALLED 114
#define IDE_CURRENT_VERSION 115
#define IDCB_CHECK_HOURLY 116
#define IDCB_INSTALL_QUIETLY 117
#define IDS_LATEST_VERSION 118
#define IDS_CURRENT_VERSION 119
#define IDB_ABOUTDIA 120
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Nächste Standardwerte für neue Objekte
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
